/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as InboxUserIdRouteImport } from './routes/inbox.$userId'
import { Route as ProductIdEditRouteImport } from './routes/product.$id.edit'
import { Route as ApiPesapalStatusRouteImport } from './routes/api/pesapal.status'
import { Route as ApiPesapalInitiateRouteImport } from './routes/api/pesapal.initiate'
import { Route as ApiPublicPesapalIpnRouteImport } from './routes/api/public/pesapal.ipn'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxUserIdRoute = InboxUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => InboxRoute,
} as any)
const ProductIdEditRoute = ProductIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProductIdRoute,
} as any)
const ApiPesapalStatusRoute = ApiPesapalStatusRouteImport.update({
  id: '/api/pesapal/status',
  path: '/api/pesapal/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPesapalInitiateRoute = ApiPesapalInitiateRouteImport.update({
  id: '/api/pesapal/initiate',
  path: '/api/pesapal/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPesapalIpnRoute = ApiPublicPesapalIpnRouteImport.update({
  id: '/api/public/pesapal/ipn',
  path: '/api/public/pesapal/ipn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRouteWithChildren
  '/invite': typeof InviteRoute
  '/kyc': typeof KycRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/inbox/$userId': typeof InboxUserIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRouteWithChildren
  '/shop/$id': typeof ShopIdRoute
  '/api/pesapal/initiate': typeof ApiPesapalInitiateRoute
  '/api/pesapal/status': typeof ApiPesapalStatusRoute
  '/product/$id/edit': typeof ProductIdEditRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRouteWithChildren
  '/invite': typeof InviteRoute
  '/kyc': typeof KycRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/inbox/$userId': typeof InboxUserIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRouteWithChildren
  '/shop/$id': typeof ShopIdRoute
  '/api/pesapal/initiate': typeof ApiPesapalInitiateRoute
  '/api/pesapal/status': typeof ApiPesapalStatusRoute
  '/product/$id/edit': typeof ProductIdEditRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRoute
  '/inbox': typeof InboxRouteWithChildren
  '/invite': typeof InviteRoute
  '/kyc': typeof KycRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/payments': typeof PaymentsRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/inbox/$userId': typeof InboxUserIdRoute
  '/legal/$doc': typeof LegalDocRoute
  '/payment/return': typeof PaymentReturnRoute
  '/product/$id': typeof ProductIdRouteWithChildren
  '/shop/$id': typeof ShopIdRoute
  '/api/pesapal/initiate': typeof ApiPesapalInitiateRoute
  '/api/pesapal/status': typeof ApiPesapalStatusRoute
  '/product/$id/edit': typeof ProductIdEditRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/inbox'
    | '/invite'
    | '/kyc'
    | '/notifications'
    | '/onboarding'
    | '/payments'
    | '/preferences'
    | '/privacy'
    | '/report'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/inbox/$userId'
    | '/legal/$doc'
    | '/payment/return'
    | '/product/$id'
    | '/shop/$id'
    | '/api/pesapal/initiate'
    | '/api/pesapal/status'
    | '/product/$id/edit'
    | '/api/public/pesapal/ipn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/inbox'
    | '/invite'
    | '/kyc'
    | '/notifications'
    | '/onboarding'
    | '/payments'
    | '/preferences'
    | '/privacy'
    | '/report'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/inbox/$userId'
    | '/legal/$doc'
    | '/payment/return'
    | '/product/$id'
    | '/shop/$id'
    | '/api/pesapal/initiate'
    | '/api/pesapal/status'
    | '/product/$id/edit'
    | '/api/public/pesapal/ipn'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/help'
    | '/inbox'
    | '/invite'
    | '/kyc'
    | '/notifications'
    | '/onboarding'
    | '/payments'
    | '/preferences'
    | '/privacy'
    | '/report'
    | '/saved'
    | '/search'
    | '/sell'
    | '/settings'
    | '/inbox/$userId'
    | '/legal/$doc'
    | '/payment/return'
    | '/product/$id'
    | '/shop/$id'
    | '/api/pesapal/initiate'
    | '/api/pesapal/status'
    | '/product/$id/edit'
    | '/api/public/pesapal/ipn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRoute
  InboxRoute: typeof InboxRouteWithChildren
  InviteRoute: typeof InviteRoute
  KycRoute: typeof KycRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentsRoute: typeof PaymentsRoute
  PreferencesRoute: typeof PreferencesRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  LegalDocRoute: typeof LegalDocRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ProductIdRoute: typeof ProductIdRouteWithChildren
  ShopIdRoute: typeof ShopIdRoute
  ApiPesapalInitiateRoute: typeof ApiPesapalInitiateRoute
  ApiPesapalStatusRoute: typeof ApiPesapalStatusRoute
  ApiPublicPesapalIpnRoute: typeof ApiPublicPesapalIpnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$userId': {
      id: '/inbox/$userId'
      path: '/$userId'
      fullPath: '/inbox/$userId'
      preLoaderRoute: typeof InboxUserIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/product/$id/edit': {
      id: '/product/$id/edit'
      path: '/edit'
      fullPath: '/product/$id/edit'
      preLoaderRoute: typeof ProductIdEditRouteImport
      parentRoute: typeof ProductIdRoute
    }
    '/api/pesapal/status': {
      id: '/api/pesapal/status'
      path: '/api/pesapal/status'
      fullPath: '/api/pesapal/status'
      preLoaderRoute: typeof ApiPesapalStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pesapal/initiate': {
      id: '/api/pesapal/initiate'
      path: '/api/pesapal/initiate'
      fullPath: '/api/pesapal/initiate'
      preLoaderRoute: typeof ApiPesapalInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pesapal/ipn': {
      id: '/api/public/pesapal/ipn'
      path: '/api/public/pesapal/ipn'
      fullPath: '/api/public/pesapal/ipn'
      preLoaderRoute: typeof ApiPublicPesapalIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxUserIdRoute: typeof InboxUserIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxUserIdRoute: InboxUserIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

interface ProductIdRouteChildren {
  ProductIdEditRoute: typeof ProductIdEditRoute
}

const ProductIdRouteChildren: ProductIdRouteChildren = {
  ProductIdEditRoute: ProductIdEditRoute,
}

const ProductIdRouteWithChildren = ProductIdRoute._addFileChildren(
  ProductIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRoute,
  InboxRoute: InboxRouteWithChildren,
  InviteRoute: InviteRoute,
  KycRoute: KycRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentsRoute: PaymentsRoute,
  PreferencesRoute: PreferencesRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  LegalDocRoute: LegalDocRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ProductIdRoute: ProductIdRouteWithChildren,
  ShopIdRoute: ShopIdRoute,
  ApiPesapalInitiateRoute: ApiPesapalInitiateRoute,
  ApiPesapalStatusRoute: ApiPesapalStatusRoute,
  ApiPublicPesapalIpnRoute: ApiPublicPesapalIpnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
